using System.Data;
using Migrator.Framework;

namespace CliqFlip.Infrastructure.Migrator.Migrations
{
	[Migration(634678604731617023)]
	public class __634678604731617023_CreateLocationsTables : Migration
	{
		public override void Up()
		{
			Database.AddTable("MajorLocations", new[]
			{
				new Column("Id", DbType.Int32, ColumnProperty.PrimaryKeyWithIdentity),
				new Column("Slug", DbType.String, 255, ColumnProperty.NotNull),
				new Column("Name", DbType.String, 255, ColumnProperty.NotNull),
				new Column("Country", DbType.String, 255),
				new Column("TimeZone", DbType.String, 255),
				new Column("TimeZoneOffsetInSeconds", DbType.String, 255),
				new Column("Latitude", DbType.String, 255),
				new Column("Longitude", DbType.String, 255),
				new Column("SlugSpecificSubset", DbType.String, 255),
				new Column("NameSpecificSubset", DbType.String, 255),
				new Column("LatitudeSpecificSubset", DbType.String, 255),
				new Column("LongitudeSpecificSubset", DbType.String, 255)
			});

			#region Insert Locations

			Database.ExecuteNonQuery(
				@"
			INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('abbotsford','Abbotsford','Canada','Pacific Time (US & Canada)','-28800','49.0568','-122.285',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('abilene','Abilene, TX','USA','Central Time (US & Canada)','-21600','32.4487','-99.7331',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('akron-canton','Akron / Canton','USA','Eastern Time (US & Canada)','-18000','41.0814','-81.519',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('albany-capital-region','Albany / Capital Region','USA','Eastern Time (US & Canada)','-18000','42.6526','-73.7562',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('albuquerque','Albuquerque','USA','Mountain Time (US & Canada)','-25200','35.0845','-106.651',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('allentown-reading','Allentown / Reading','USA','Eastern Time (US & Canada)','-18000','40.6084','-75.4902',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('amarillo','Amarillo','USA','Central Time (US & Canada)','-21600','35.222','-101.831',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('anchorage','Anchorage','USA','Alaska','-32400','61.2181','-149.9',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('ann-arbor','Ann Arbor','USA','Eastern Time (US & Canada)','-18000','42.2814','-83.7483',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('asheville','Asheville','USA','Eastern Time (US & Canada)','-18000','35.6009','-82.554',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('athens-ga','Athens, GA','USA','Eastern Time (US & Canada)','-18000','33.9558','-83.3824',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('atlanta','Atlanta','USA','Eastern Time (US & Canada)','-18000','33.7545','-84.3897',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('augusta','Augusta','USA','Eastern Time (US & Canada)','-18000','33.4742','-82.0097',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('austin','Austin','USA','Central Time (US & Canada)','-21600','30.2687','-97.7452',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('bakersfield','Bakersfield','USA','Pacific Time (US & Canada)','-28800','35.3733','-119.019',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('baltimore','Baltimore','USA','Eastern Time (US & Canada)','-18000','39.2943','-76.6143',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('barrie','Barrie','Canada','Eastern Time (US & Canada)','-18000','44.3812','-79.687',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('baton-rouge','Baton Rouge','USA','Central Time (US & Canada)','-21600','30.4507','-91.1545',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('beaumont','Beaumont, TX','USA','Central Time (US & Canada)','-21600','30.0802','-94.1266',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('billings','Billings / Bozeman','USA','Mountain Time (US & Canada)','-25200','45.7833','-108.501',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('birmingham','Birmingham','USA','Central Time (US & Canada)','-21600','33.5207','-86.8025',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('bloomington-in','Bloomington, IN','USA','Eastern Time (US & Canada)','-18000','39.1653','-86.5264',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('boise','Boise','USA','Mountain Time (US & Canada)','-25200','43.6137','-116.238',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('boston','Boston','USA','Eastern Time (US & Canada)','-18000','42.3589','-71.0578',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('buffalo','Buffalo','USA','Eastern Time (US & Canada)','-18000','42.8864','-78.8784',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('calgary','Calgary','Canada','Mountain Time (US & Canada)','-25200','51.045','-114.057',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('cape-breton','Cape Breton','Canada','Atlantic Time (Canada)','-14400','46.15','-60.1667',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('cedar-rapids-iowa-city','Cedar Rapids / Iowa City','USA','Central Time (US & Canada)','-21600','41.9625','-91.6918',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('central-jersey','Central Jersey','USA','Eastern Time (US & Canada)','-18000','40.2171','-74.7429',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('charleston','Charleston','USA','Eastern Time (US & Canada)','-18000','32.7766','-79.9309',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('charlotte','Charlotte','USA','Eastern Time (US & Canada)','-18000','35.2314','-80.8458',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('chattanooga','Chattanooga','USA','Eastern Time (US & Canada)','-18000','35.0456','-85.3097',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('chicago','Chicago','USA','Central Time (US & Canada)','-21600','41.8795','-87.6243',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('cincinnati','Cincinnati','USA','Eastern Time (US & Canada)','-18000','39.148','-84.477',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('cleveland','Cleveland','USA','Eastern Time (US & Canada)','-18000','41.4995','-81.6954',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('colorado-springs','Colorado Springs','USA','Mountain Time (US & Canada)','-25200','38.8339','-104.821',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('columbia','Columbia','USA','Eastern Time (US & Canada)','-18000','34.0007','-81.0348',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('columbia-mo','Columbia, MO','USA','Central Time (US & Canada)','-21600','38.9481','-92.3268',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('columbus','Columbus','USA','Eastern Time (US & Canada)','-18000','39.9612','-82.9988',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('columbus-ga','Columbus GA','USA','Eastern Time (US & Canada)','-18000','32.461','-84.9877',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('corpus-christi','Corpus Christi','USA','Central Time (US & Canada)','-21600','27.8006','-97.3964',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('dallas','Dallas','USA','Central Time (US & Canada)','-21600','32.7811','-96.7971',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('dayton','Dayton','USA','Eastern Time (US & Canada)','-18000','39.7589','-84.1916',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('daytona-beach','Daytona Beach','USA','Eastern Time (US & Canada)','-18000','29.1988','-81.089',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('denver','Denver','USA','Mountain Time (US & Canada)','-25200','39.7551','-104.988',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('des-moines','Des Moines','USA','Central Time (US & Canada)','-21600','41.6005','-93.6091',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('detroit','Detroit','USA','Eastern Time (US & Canada)','-18000','42.3314','-83.0458',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('edmonton','Edmonton','Canada','Mountain Time (US & Canada)','-25200','53.5436','-113.49',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('el-paso','El Paso','USA','Mountain Time (US & Canada)','-25200','31.7587','-106.487',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('erie','Erie','USA','Eastern Time (US & Canada)','-18000','42.1292','-80.0851',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('eugene','Eugene','USA','Pacific Time (US & Canada)','-28800','44.0521','-123.087',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('evansville','Evansville','USA','Central Time (US & Canada)','-21600','37.9748','-87.5558',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('fairfield-county','Fairfield County','USA','Eastern Time (US & Canada)','-18000','41.3802','-73.4553',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('fort-lauderdale','Fort Lauderdale','USA','Eastern Time (US & Canada)','-18000','26.1223','-80.1434',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('fort-myers-cape-coral','Fort Myers / Cape Coral','USA','Eastern Time (US & Canada)','-18000','26.6406','-81.8723',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('fort-wayne','Fort Wayne','USA','Eastern Time (US & Canada)','-18000','41.1306','-85.1289',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('fort-worth','Fort Worth','USA','Central Time (US & Canada)','-21600','32.7254','-97.3208',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('appleton','Fox Cities','USA','Central Time (US & Canada)','-21600','44.2619','-88.4154',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('fresno','Fresno','USA','Pacific Time (US & Canada)','-28800','36.7477','-119.772',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('gainesville','Gainesville','USA','Eastern Time (US & Canada)','-18000','29.6516','-82.3248',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('grand-rapids','Grand Rapids','USA','Eastern Time (US & Canada)','-18000','42.9634','-85.6681',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('green-bay','Green Bay','USA','Central Time (US & Canada)','-21600','44.5192','-88.0198',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('greenville','Greenville','USA','Eastern Time (US & Canada)','-18000','34.8526','-82.394',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('halifax','Halifax','Canada','Atlantic Time (Canada)','-14400','44.6489','-63.5753',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('hampton-roads','Hampton Roads','USA','Eastern Time (US & Canada)','-18000','36.8529','-75.978',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('harrisburg','Harrisburg / Lancaster','USA','Eastern Time (US & Canada)','-18000','40.2737','-76.8844',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('hartford','Hartford','USA','Eastern Time (US & Canada)','-18000','41.7637','-72.6851',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('honolulu','Honolulu','USA','Hawaii','-36000','21.3069','-157.858',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('houston','Houston','USA','Central Time (US & Canada)','-21600','29.76','-95.3625',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('huntsville','Huntsville','USA','Central Time (US & Canada)','-21600','34.7304','-86.5861',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('indianapolis','Indianapolis','USA','Eastern Time (US & Canada)','-18000','39.767','-86.1563',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('inland-empire','Inland Empire','USA','Pacific Time (US & Canada)','-28800','34.1083','-117.29',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('jackson','Jackson','USA','Central Time (US & Canada)','-21600','32.2988','-90.1848',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('jacksonville','Jacksonville','USA','Eastern Time (US & Canada)','-18000','30.3322','-81.6556',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('kalamazoo','Kalamazoo','USA','Eastern Time (US & Canada)','-18000','42.2917','-85.5872',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('kansas-city','Kansas City','USA','Central Time (US & Canada)','-21600','39.0997','-94.5786',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('kelowna','Kelowna','Canada','Pacific Time (US & Canada)','-28800','49.8799','-119.45',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('kingston','Kingston / Belleville','Canada','Eastern Time (US & Canada)','-18000','44.2636','-76.5034',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('kitchener-waterloo','Kitchener - Waterloo','Canada','Eastern Time (US & Canada)','-18000','43.4343','-80.4777',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('knoxville','Knoxville','USA','Eastern Time (US & Canada)','-18000','35.9606','-83.9207',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('lakeland','Lakeland','USA','Eastern Time (US & Canada)','-18000','28.0395','-81.9498',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('lansing','Lansing','USA','Eastern Time (US & Canada)','-18000','42.7325','-84.5555',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('las-vegas','Las Vegas','USA','Pacific Time (US & Canada)','-28800','36.1146','-115.173',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('lexington','Lexington','USA','Eastern Time (US & Canada)','-18000','38.0317','-84.4951',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('lincoln','Lincoln','USA','Central Time (US & Canada)','-21600','40.8069','-96.6817',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('little-rock','Little Rock','USA','Central Time (US & Canada)','-21600','34.7465','-92.2896',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('london','London, ON','Canada','Eastern Time (US & Canada)','-18000','42.9794','-81.2461',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('long-island','Long Island','USA','Eastern Time (US & Canada)','-18000','40.8168','-73.0661',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('los-angeles','Los Angeles','USA','Pacific Time (US & Canada)','-28800','34.0522','-118.243','los-angeles','Los Angeles','34.0305','-118.318')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('los-angeles','Los Angeles','USA','Pacific Time (US & Canada)','-28800','34.0522','-118.243','san-gabriel-valley','San Gabriel Valley','34.0745','-118.011')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('los-angeles','Los Angeles','USA','Pacific Time (US & Canada)','-28800','34.0522','-118.243','san-fernando-valley','San Fernando Valley','34.2221','-118.446')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('louisville','Louisville','USA','Eastern Time (US & Canada)','-18000','38.2542','-85.7594',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('lubbock','Lubbock','USA','Central Time (US & Canada)','-21600','33.5779','-101.855',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('macon','Macon','USA','Eastern Time (US & Canada)','-18000','32.8407','-83.6324',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('madison','Madison','USA','Central Time (US & Canada)','-21600','43.0731','-89.4012',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('memphis','Memphis','USA','Central Time (US & Canada)','-21600','35.1495','-90.049',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('miami','Miami','USA','Eastern Time (US & Canada)','-18000','25.7743','-80.1903',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('midland-odessa','Midland / Odessa','USA','Central Time (US & Canada)','-21600','31.9727','-102.392',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('milwaukee','Milwaukee','USA','Central Time (US & Canada)','-21600','43.0389','-87.9065',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('minneapolis-stpaul','Minneapolis / St Paul','USA','Central Time (US & Canada)','-21600','44.98','-93.2638',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('mobile-baldwin-county','Mobile / Baldwin County','USA','Central Time (US & Canada)','-21600','30.6944','-88.0431',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('modesto','Modesto','USA','Pacific Time (US & Canada)','-28800','37.6391','-120.997',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('montgomery','Montgomery','USA','Central Time (US & Canada)','-21600','32.3668','-86.3',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('napa-sonoma','Napa / Sonoma','USA','Pacific Time (US & Canada)','-28800','38.4405','-122.714',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('naples','Naples','USA','Eastern Time (US & Canada)','-18000','26.142','-81.7948',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('nashville','Nashville','USA','Central Time (US & Canada)','-21600','36.1659','-86.7844',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('new-orleans','New Orleans','USA','Central Time (US & Canada)','-21600','29.9546','-90.0751',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('new-york','New York City','USA','Eastern Time (US & Canada)','-18000','40.7561','-73.987',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('north-jersey','North Jersey','USA','Eastern Time (US & Canada)','-18000','40.9598','-74.2219',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('ocala','Ocala','USA','Eastern Time (US & Canada)','-18000','29.1872','-82.1401',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('ogden','Ogden','USA','Mountain Time (US & Canada)','-25200','41.223','-111.974',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('oklahoma-city','Oklahoma City','USA','Central Time (US & Canada)','-21600','35.4676','-97.5164',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('omaha','Omaha','USA','Central Time (US & Canada)','-21600','41.254','-95.9993',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('orange-county','Orange County','USA','Pacific Time (US & Canada)','-28800','33.7456','-117.868',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('orlando','Orlando','USA','Eastern Time (US & Canada)','-18000','28.5383','-81.3792',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('ottawa','Ottawa','Canada','Eastern Time (US & Canada)','-18000','45.4116','-75.6982',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('palm-beach','Palm Beach','USA','Eastern Time (US & Canada)','-18000','26.7056','-80.0364',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('pensacola','Pensacola / Emerald Coast','USA','Central Time (US & Canada)','-21600','30.4213','-87.2169',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('philadelphia','Philadelphia','USA','Eastern Time (US & Canada)','-18000','39.9516','-75.1638',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('phoenix','Phoenix','USA','Arizona','-25200','33.4483','-112.074',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('piedmont-triad','Piedmont Triad','USA','Eastern Time (US & Canada)','-18000','36.0726','-79.792',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('pittsburgh','Pittsburgh','USA','Eastern Time (US & Canada)','-18000','40.4406','-79.9959',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('portland','Portland','USA','Pacific Time (US & Canada)','-28800','45.5235','-122.676',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('portland-me','Portland, ME','USA','Eastern Time (US & Canada)','-18000','43.6615','-70.2553',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('providence','Providence','USA','Eastern Time (US & Canada)','-18000','41.824','-71.4128',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('raleigh-durham','Raleigh / Durham','USA','Eastern Time (US & Canada)','-18000','35.7721','-78.6386',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('regina','Regina','Canada','Central Time (US & Canada)','-21600','50.45','-104.61',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('reno','Reno','USA','Pacific Time (US & Canada)','-28800','39.5296','-119.814',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('richmond','Richmond','USA','Eastern Time (US & Canada)','-18000','37.533','-77.467',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('rio-grande-valley','Rio Grande Valley','USA','Central Time (US & Canada)','-21600','26.2034','-98.23',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('roanoke','Roanoke','USA','Eastern Time (US & Canada)','-18000','37.271','-79.9414',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('rochester','Rochester','USA','Eastern Time (US & Canada)','-18000','43.1548','-77.6156',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('rockford','Rockford','USA','Central Time (US & Canada)','-21600','42.2711','-89.094',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('sacramento','Sacramento','USA','Pacific Time (US & Canada)','-28800','38.5816','-121.494',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('salem-or','Salem OR','USA','Pacific Time (US & Canada)','-28800','44.9429','-123.035',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('salt-lake-city','Salt Lake City','USA','Mountain Time (US & Canada)','-25200','40.7608','-111.891',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('san-angelo','San Angelo','USA','Central Time (US & Canada)','-21600','31.4406','-100.452',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('san-antonio','San Antonio','USA','Central Time (US & Canada)','-21600','29.4241','-98.4936',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('san-diego','San Diego','USA','Pacific Time (US & Canada)','-28800','32.7188','-117.164',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('san-francisco','San Francisco','USA','Pacific Time (US & Canada)','-28800','37.7752','-122.419','san-francisco','San Francisco','37.7808','-122.418')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('san-francisco','San Francisco','USA','Pacific Time (US & Canada)','-28800','37.7752','-122.419','east-bay','East Bay','37.8151','-122.24')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('san-jose','San Jose','USA','Pacific Time (US & Canada)','-28800','37.3394','-121.895',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('santa-barbara','Santa Barbara','USA','Pacific Time (US & Canada)','-28800','34.3996','-119.713',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('santa-clarita','Santa Clarita','USA','Pacific Time (US & Canada)','-28800','34.3917','-118.543',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('santa-cruz','Santa Cruz / Monterey','USA','Pacific Time (US & Canada)','-28800','36.9741','-122.031',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('saskatoon','Saskatoon','Canada','Central Time (US & Canada)','-21600','52.1344','-106.648',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('savannah-hilton-head','Savannah / Hilton Head','USA','Eastern Time (US & Canada)','-18000','32.0835','-81.0998',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('seattle','Seattle','USA','Pacific Time (US & Canada)','-28800','47.621','-122.347','tacoma','Tacoma','47.249','-122.465')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('seattle','Seattle','USA','Pacific Time (US & Canada)','-28800','47.621','-122.347','seattle','Seattle','47.6113','-122.333')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('shreveport-bossier','Shreveport / Bossier','USA','Central Time (US & Canada)','-21600','32.5252','-93.7502',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('sioux-falls','Sioux Falls','USA','Central Time (US & Canada)','-21600','43.55','-96.7003',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('south-bend','South Bend','USA','Eastern Time (US & Canada)','-18000','41.6834','-86.25',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('albany-ga','Southern Georgia','USA','Eastern Time (US & Canada)','-18000','31.5785','-84.1557',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('spokane-coeur-dalene','Spokane / Coeur d''Alene','USA','Pacific Time (US & Canada)','-28800','47.6588','-117.426',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('springfield-mo','Springfield MO','USA','Central Time (US & Canada)','-21600','37.2153','-93.2982',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('springfield-ma','Springfield, MA','USA','Eastern Time (US & Canada)','-18000','42.1015','-72.5898',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('stcatharines-niagara','St Catharines-Niagara','Canada','Eastern Time (US & Canada)','-18000','43.588','-77.7452',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('st-johns','St John''s','Canada','Newfoundland','-12600','47.5615','-52.7127',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('stlouis','St Louis','USA','Central Time (US & Canada)','-21600','38.6275','-90.1984',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('stockton','Stockton','USA','Pacific Time (US & Canada)','-28800','37.9577','-121.291',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('sudbury','Sudbury / North Bay','Canada','Eastern Time (US & Canada)','-18000','46.49','-81.01',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('syracuse','Syracuse','USA','Eastern Time (US & Canada)','-18000','43.0481','-76.1474',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('tallahassee','Tallahassee','USA','Eastern Time (US & Canada)','-18000','30.4383','-84.2807',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('tampa-bay-area','Tampa Bay Area','USA','Eastern Time (US & Canada)','-18000','27.9814','-82.4511',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('toledo','Toledo','USA','Eastern Time (US & Canada)','-18000','41.6639','-83.5552',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('topeka-lawrence','Topeka / Lawrence','USA','Central Time (US & Canada)','-21600','39.0558','-95.689',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('greater-toronto-area','Toronto (GTA)','Canada','Eastern Time (US & Canada)','-18000','43.6702','-79.3868',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('tucson','Tucson','USA','Pacific Time (US & Canada)','-28800','32.2217','-110.926',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('tulsa','Tulsa','USA','Central Time (US & Canada)','-21600','36.154','-95.9928',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('vancouver','Vancouver','Canada','Pacific Time (US & Canada)','-28800','49.2636','-123.139',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('ventura-county','Ventura County','USA','Pacific Time (US & Canada)','-28800','34.3705','-119.139',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('victoria','Victoria','Canada','Pacific Time (US & Canada)','-28800','48.4286','-123.366',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('washington-dc','Washington DC','USA','Eastern Time (US & Canada)','-18000','38.8921','-77.0241','dc-metro','The District','38.9066','-77.0166')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('washington-dc','Washington DC','USA','Eastern Time (US & Canada)','-18000','38.8921','-77.0241','northern-virginia','Northern Virginia','38.8209','-77.291')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('washington-dc','Washington DC','USA','Eastern Time (US & Canada)','-18000','38.8921','-77.0241','montgomery-county','Montgomery County','39.0772','-77.1262')
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('westchester-county','Westchester County','USA','Eastern Time (US & Canada)','-18000','41.122','-73.7949',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('wichita','Wichita','USA','Central Time (US & Canada)','-21600','37.6922','-97.3375',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('wilmington-newark','Wilmington-Newark','USA','Eastern Time (US & Canada)','-18000','39.7092','-75.6816',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('windsor','Windsor','Canada','Eastern Time (US & Canada)','-18000','42.2927','-82.9933',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('winnipeg','Winnipeg','Canada','Central Time (US & Canada)','-21600','49.8861','-97.1529',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('worcester','Worcester','USA','Eastern Time (US & Canada)','-18000','42.2626','-71.8023',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('youngstown','Youngstown','USA','Eastern Time (US & Canada)','-18000','41.0998','-80.6495',NULL,NULL,NULL,NULL)
INSERT MajorLocations(slug,name,country,timezone,timezoneOffsetInSeconds,Latitude,Longitude,SlugSpecificSubset,NameSpecificSubset,LatitudeSpecificSubset,LongitudeSpecificSubset) VALUES('online','Online',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
			");

			#endregion

			Database.ExecuteNonQuery(@"ALTER TABLE [dbo].[MajorLocations] ADD [GeoLocation] GEOGRAPHY;");
			Database.ExecuteNonQuery(
				@"
				UPDATE [dbo].[MajorLocations]
				SET [GeoLocation] = geography::STPointFromText('POINT(' + CAST(ISNULL([LongitudeSpecificSubset],[Longitude]) AS VARCHAR(20)) + ' ' + 
                CAST(ISNULL([LatitudeSpecificSubset],[Latitude]) AS VARCHAR(20)) + ')', 4326)");

			Database.AddTable("Locations", new[]
			{
				new Column("Id", DbType.Int32, ColumnProperty.PrimaryKeyWithIdentity),
				new Column("CountryCode", DbType.String, 255, ColumnProperty.NotNull),
				new Column("CountryName", DbType.String, 255, ColumnProperty.NotNull),
				new Column("RegionCode", DbType.String, 255, ColumnProperty.NotNull),
				new Column("RegionName", DbType.String, 255, ColumnProperty.NotNull),
				new Column("MetroCode", DbType.String, 255),
				new Column("County", DbType.String, 255, ColumnProperty.NotNull),
				new Column("Street", DbType.String, 255, ColumnProperty.NotNull),
				new Column("City", DbType.String, 255, ColumnProperty.NotNull),
				new Column("ZipCode", DbType.String, 255, ColumnProperty.NotNull),
				new Column("AreaCode", DbType.String, 255),
				new Column("Latitude", DbType.Single, ColumnProperty.NotNull),
				new Column("Longitude", DbType.Single, ColumnProperty.NotNull),
				new Column("MajorLocationId", DbType.Int32, ColumnProperty.NotNull)
			});

			Database.AddColumn("Users", "LocationId", DbType.Int32, ColumnProperty.NotNull);

			Database.AddForeignKey("FK_Users_Locations", "Users", "LocationId", "Locations", "Id");
			Database.AddForeignKey("FK_Locations_MajorLocations", "Locations", "MajorLocationId", "MajorLocations", "Id");
		}

		public override void Down()
		{
			Database.RemoveForeignKey("Users", "FK_Users_Locations");
			Database.RemoveForeignKey("Locations", "FK_Locations_MajorLocations");
			Database.RemoveTable("Locations");
			Database.RemoveTable("MajorLocations");
		}
	}
}