CREATE TABLE [dbo].[SchemaInfo] (
    [Version] BIGINT NOT NULL,
    PRIMARY KEY CLUSTERED ([Version] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

